version: '3'
services:
  nginxphp:
    restart: always
    container_name: frontend1
    build: /home/chris/Dev/Dockerfiles/nginx-php
    networks:
     - dbconnection
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./nginx/sites-available:/etc/nginx/sites-enabled
     - ../www:/var/www

  mariadb:
    restart: always
    container_name: mariadb1
    build: /home/chris/Dev/Dockerfiles/mariadb
    networks:
     - dbconnection
    ports:
     - "3306:3306"

  mongodb:
    restart: always
    container_name: mongodb1
    build: /home/chris/Dev/Dockerfiles/mongodb
    networks:
     - dbconnection
    ports:
     - "27017:27017"
     - "27018:27018"
    volumes:
     - ./volumes/var/lib/mongodb/:/var/lib/mongodb
     - ../data:/var/data

  elasticsearch:
    restart: always
    container_name: es1
    build: /home/chris/Dev/Dockerfiles/elasticsearch
    networks:
     - dbconnection
    ports:
     - "9100:9100"
     - "9200:9200"
     - "9300:9300"

  elastichead:
    restart: always
    container_name: elastichead
    build: /home/chris/Dev/Dockerfiles/elastic-head
    networks:
     - dbconnection
    ports:
     - "8080:8080"

  beanstalk:
    restart: always
    container_name: beanstalk
    build: /home/chris/Dev/Dockerfiles/beanstalk
    networks:
     - dbconnection
    ports:
     - "8282:8282"
     - "11300:11300"

  nodejs:
    restart: always
    container_name: nodejs1
    build: /home/chris/Dev/Dockerfiles/nodeJs
    volumes:
     - ../crawler:/var/crawler
    networks:
     - dbconnection

networks:
  dbconnection:
    driver: bridge
